name: Build and push Docker images

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta for Base image
        id: base_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/base
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Meta for Webserver image
        id: webserver_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/webserver
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Meta for App image
        id: app_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/app
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Meta for Queue Worker image
        id: queue_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/queue
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Meta for Schedule Runner image
        id: schedule_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/schedule
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Base image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile
          tags: ${{ steps.base_meta.outputs.tags }}

      - name: Build and push Webserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/webserver.Dockerfile
          tags: ${{ steps.webserver_meta.outputs.tags }}

      - name: Build and push App image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/app.Dockerfile
          tags: ${{ steps.app_meta.outputs.tags }}

      - name: Build and push Queue Worker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/queue.Dockerfile
          tags: ${{ steps.queue_meta.outputs.tags }}

      - name: Build and push Schedule Runner image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker
          file: docker/schedule.Dockerfile
          tags: ${{ steps.schedule_meta.outputs.tags }}
